# Introduction to NumPy
 This is a short numpy tutorial for RVL224 students.
 
 In this section, you will learn:
 
 * what is numpy.
 
 * How to use numpy to do math operatons.
 
## What is NumPy?

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

## Array

Numpy provide a special array object called **numpy array**, which can contains a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [1]:
import numpy as np       # You must import numpy first in order to use all the tools it provides

a = np.array([1, 2, 3])  # Create a rank 1 array which is [1,2,3]
print (type(a))            # Prints "<type 'numpy.ndarray'>"
print (a.shape)            # Prints "(3,)"
print (a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                 # Change an element of the array
print (a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print (b.shape)                     # Prints "(2, 3)"
print (b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<type 'numpy.ndarray'>
(3,)
(1, 2, 3)
[5 2 3]
(2, 3)
(1, 2, 4)


Numpy also provides many functions to create arrays:

In [2]:
a = np.zeros((2,2))  # Create an array of all zeros
print (a)              # Prints "[[ 0.  0.]
                     #          [ 0.  0.]]"

[[ 0.  0.]
 [ 0.  0.]]


In [3]:
b = np.ones((1,2))   # Create an array of all ones
print (b)             # Prints "[[ 1.  1.]]"

[[ 1.  1.]]


In [4]:
c = np.full((2,2), 7) # Create a constant array
print (c)               # Prints "[[ 7.  7.]
                      #          [ 7.  7.]]"

[[7 7]
 [7 7]]


In [5]:
d = np.eye(2)        # Create a 2x2 identity matrix
print (d)              # Prints "[[ 1.  0.]
                     #          [ 0.  1.]]"

[[ 1.  0.]
 [ 0.  1.]]


In [18]:
e = np.random.random((2,2)) # Create an array filled with random values
print (e)                     

[[ 0.36600741  0.86009381]
 [ 0.82203177  0.99775204]]


## Array indexing

Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [6]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]


# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print (a[0, 1])   # Prints "2"
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print (a[0, 1] )  # Prints "77"

2
77


**Integer array indexing**:

In [7]:
import numpy as np

# Create the array [[1,2]
#                   [3,4]
#                   [5,6]]
a = np.array([[1,2], [3, 4], [5, 6]]) 


# An example of integer array indexing.
# The returned array will have shape (3,) and 
print( a[[0, 1, 2], [0, 1, 0]] )  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print( np.array([a[0, 0], a[1, 1], a[2, 0]]) ) # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print( a[[0, 0], [1, 1]] ) # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print( np.array([a[0, 1], a[0, 1]]) ) # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


## Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [8]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print (x + y)
print (np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [9]:
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print (x - y)
print (np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [10]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print (x * y)
print (np.multiply(x, y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


In [11]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print (x / y)
print (np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [26]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print (np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


Note that `  * ` is elementwise multiplication in numpy, not matrix multiplication. So we must use **dot** function instead to perform matrix multiplication or inner product of vectors

In [12]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print (v.dot(w))
print (np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print (x.dot(v))
print (np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print (x.dot(y))
print (np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [13]:
x = np.array([[1,2],[3,4]])

print (np.sum(x))  # Compute sum of all elements; prints "10"
print (np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print (np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [14]:
x = np.array([[1,2], [3,4]])
print (x )   # Prints "[[1 2]
           #          [3 4]]"
print (x.T)  # Prints "[[1 3]
           #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print (v )   # Prints "[1 2 3]"
print (v.T ) # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## Exercise 1

Write a function f(x) that perform the following caculation:

$$
f(x) = \frac{1}{\exp(x^{-1})}
$$

your input x should except any shape of vector


In [18]:
def f(x):
    """
    
    your code here
    
    """
    return y



## Exercise 2

Write a function that perform the following:
$$
\text{S}(x_i) = \frac{\exp(x_i)}{\sum_j \exp(x_j)}
$$

where x is a vector of any length, for example [2,3,5,0,1]